Add content table
debian-cryptoanarchy/cryptoanarchy-deb-repo-builder pull request #141
Opened 2021-04-02 14:58 UTC by taxmeifyoucan

README got pretty long and basic content table would help users to navigate.

2021-04-02 16:31 UTC, MaxHillebrand approved these changes
ACK  448497d

2021-04-02 18:42 UTC, Kixunil commented
There's one in the upper-left corner, it was [added 8 days ago](https://github.com/isaacs/github/issues/215#issuecomment-807688648)

I do think that having something more visible is nice but we will have to keep this in sync. Maybe simple "Check upper-left corner of README for ToC?" What do you think?

2021-04-02 22:15 UTC, taxmeifyoucan commented
@Kixunil Well, even I haven't noticed it :D I see it is github feature, this way it is not dependent on software reading md file

2021-04-03 07:04 UTC, MaxHillebrand commented
woah, that automated ToC is super useful actually, didn't know this got added, nice!

2021-04-03 09:09 UTC, Kixunil commented
How about having a smaller table with "featured topics"? I would consider these topics featured:

* How to setup
* Bug reporting
* Documentation
* Development

And perhaps leave a note about GH feature for the upcoming few months until people learn about it.

2021-04-10 08:45 UTC, Kixunil commented
@taxmeifyoucan do you intend to update this PR based on my suggestion (smaller table and a hint)?

2021-04-11 10:27 UTC, Kixunil requested changes

2021-04-11 10:27 UTC, Kixunil commented on README.md
> +gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 3D9E81D3CA76CDCBE768C4B4DC6B4F8E60B8CF4C
Please remove accidental space

2021-04-11 11:08 UTC, Kixunil approved these changes
Thanks!

2021-04-11 11:08 UTC, merged