Set bitcoind log file under /var/log
debian-cryptoanarchy/cryptoanarchy-deb-repo-builder pull request #196
Opened 2022-03-25 06:09 UTC by HollowMan6

Resolve #194
![](https://user-images.githubusercontent.com/43995067/160064309-ec0f78fe-0a32-4956-995d-0ca0b1d5f114.png)

Signed-off-by: Hollow Man <hollowman@opensuse.org>

2022-03-28 14:43 UTC, Kixunil requested changes
Thanks! Just missing some minor details.

2022-03-28 14:43 UTC, Kixunil commented on pkg_specs/bitcoin-@variant.sps
> +create = { mode = 755, owner = "$service", group = "$service" }
Better let bitcoind create it, we don't need to. (IOW, delete this line; note that mode would've been incorrect too)
However the parent should be created, ideally by systemd - add:

```
LogsDirectory=bitcoin-{variant}
```

to `extra_service_config`

2022-03-28 14:43 UTC, Kixunil commented on pkg_specs/bitcoin-@variant.sps
> +summary = "File containing the bitcoind debug logs"
Would be nice to mention the network, e.g. "File containing the bitcoind debug logs {variant}"

2022-03-29 01:41 UTC, HollowMan6 commented
@Kixunil Done! Thanks for reviewing.

2022-08-13 18:19 UTC, Kixunil commented
WTF, I'd swear I've merged this. Let's ignore the failed test, it's not relevant to this.

2022-08-13 18:22 UTC, Kixunil commented
Oh, wait, I know why I didn't mere. The locations are not synchronized. It Either has to be a hidden var to prevent changing or definitions must read the configuration.

2022-08-14 00:11 UTC, HollowMan6 commented
Oh okay, just make the definitions read the configuration as I think that would be better to prevent the log location from changing.

2022-08-14 06:38 UTC, merged