[SoB] Add GitHub workflow for CI
debian-cryptoanarchy/cryptoanarchy-deb-repo-builder pull request #198
Opened 2022-03-26 03:47 UTC by HollowMan6

This demo GitHub Actions CI can be triggered manually, or by sending PRs as well as pushing directly to the master branch. The demo CI first builds the running docker environment, then with the docker environment, builds the CADR packages, and then uploads the built Debian packages to Artifacts (I have already runned this workflow in another repo, above steps are all successful https://github.com/HollowMan6/build-cryptoanarchy-deb-repo-builder/actions/runs/2042963652 ). Finally test the CADR just built. However, tests in the CI have failed for some strange reasons https://github.com/HollowMan6/build-cryptoanarchy-deb-repo-builder/runs/5700123801?check_suite_focus=true . I have no idea whether its some dependency errors or not, maybe some adaptation to the CI about the test scripts should be done.

Signed-off-by: Hollow Man <hollowman@opensuse.org>

2022-03-26 10:26 UTC, HollowMan6 commented
Now for sure that the test errors are related to some dependencies since the CI generated packages can smoothly run test on my Debian 10 PC. Will figure out those dependencies later.

![image](https://user-images.githubusercontent.com/43995067/160235372-c909ff9f-2360-4dc0-9d81-9ecc713a00f2.png)

![image](https://user-images.githubusercontent.com/43995067/160235236-c5e87fc6-3070-457c-aa54-86873c27b3d9.png)

2022-03-27 04:46 UTC, HollowMan6 commented
Finally find the culprit! CADR works by using unshare to separate a namespace which can't be supported inside a docker container. Will find some virtual machines to test. First will check if [Kata Containers](https://katacontainers.io/) will work in this case as it implements lightweight virtual machines that have their own kernel.
![image](https://user-images.githubusercontent.com/43995067/160266956-e69ba356-1637-4648-99d6-d3f3ad530807.png)

2022-03-28 14:50 UTC, Kixunil commented
It looks like the pace fills up by the chain in parallel. I suggest skip mainnet tests for now.

2022-03-29 06:08 UTC, HollowMan6 commented
> It looks like the pace fills up by the chain in parallel. I suggest skip mainnet tests for now.

OK, got it.

> One more thing: I used apt in tests but it really should be apt-get. I was going to open a new issue but since it complicates this one maybe it's better to do it as a part of this. What do you think?

You mean the warning `WARNING: apt does not have a stable CLI interface. Use with caution in scripts.`?  Yeah, that's OK. I will change all the `apt` into `apt-install` in a separate PR for you to merge later when the test goes smoothly.

2022-03-29 14:05 UTC, Kixunil commented
> You mean the warning

That too but also you simply having to install it first. Only `apt-get` is present on a clean system, so just use that and don't install `apt`. If you don't feel like doing such change a separate PR is OK.

2022-03-30 07:41 UTC, HollowMan6 commented on Makefile
> +TEST_ALL_PACKAGES=bitcoind bitcoin-mainnet bitcoin-regtest bitcoin-pruned-mainnet bitcoin-fullchain-mainnet bitcoin-fullchain-regtest bitcoin-txindex-mainnet bitcoin-zmq-mainnet bitcoin-zmq-regtest b
Hi @Kixunil ! Is that a typo for `btc-transmuter-system-`? I've changed it into `btc-transmuter-system-regtest` here.

2022-03-30 09:41 UTC, HollowMan6 commented
Now the test can be successful on GitHub Actions when only test with regtest and skipping the issues mentioned:
- https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder/pull/200#issuecomment-1082828541
- https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder/issues/202

Test Result:
https://github.com/HollowMan6/build-cryptoanarchy-deb-repo-builder/runs/5750416035?check_suite_focus=true

2022-05-21 14:11 UTC, HollowMan6 commented
Now the test can be successful on GitHub Actions when only test with regtest and after these PRs get merged:
- [ ] #200 
- [ ] #201 
- [ ] #203 
- [ ] #204 

Test CI Running Result:
https://github.com/HollowMan6/build-cryptoanarchy-deb-repo-builder/runs/6537201901?check_suite_focus=true

Next steps (tests available with mainnet) will need to build VMs to set up self-hosted runners for GitHub Actions.

2022-07-22 03:53 UTC, HollowMan6 commented
Hi @Kixunil , just like what I mentioned in the discord:

> I've just come up with a new way for testing. Maybe we can use the divide and conquer to bypass the short of disk space issue when testing mainnet. I can see that the make test is composed of make test-here-basic-% and make test-here-upgrade-%(% for package name), maybe we can just use the matrix in GitHub Actions https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#using-a-matrix-strategy to test each package in separate environment, and then the disk space would be enough. What do you think?

I have now successfully implemented and tested that method, and it works! https://github.com/HollowMan6/build-cryptoanarchy-deb-repo-builder/actions/runs/2715251380 So right now it's the full test and guess we have reached the project goal! https://www.summerofbitcoin.org/project-ideas-details?recordId=recaklAlmMd5cHfdq 🙌🏽

The ci can be successful with the following PRs get merged first:

- [ ] #200 
- [ ] #201 
- [ ] #203 
- [ ] https://github.com/Kixunil/debcrafter/pull/53

I guess you are busy now. When you have time, would you mind review these PRs? Thanks in advance.

2022-08-08 01:47 UTC, HollowMan6 commented
Hi @Kixunil , would you mind review/merge this PR as well as the PRs I mentioned in [my last comment](https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder/pull/198#issuecomment-1192151728) ***WITHIN THIS WEEK***? The Summer of Bitcoin 2022 project is going to [end soon](https://www.summerofbitcoin.org/how-it-works/#timeline) and next week I will have to submit the final report. Thanks in advance!

2022-08-08 13:47 UTC, Kixunil commented
Hi, sorry, I had my testing setup messed up and had trouble testing but I figured it out and merged some. I will look at the others soon. This week is realistic.

2022-08-08 14:00 UTC, Kixunil requested changes
Did only review part since I have to go now. `--locked` needs to be fixed but so far it looks nice.

2022-08-09 06:06 UTC, HollowMan6 commented on Dockerfile
> +    cargo install --git https://github.com/Kixunil/debcrafter && \
Fixed!

2022-08-09 06:07 UTC, HollowMan6 commented on Dockerfile
> +    dpkg -i packages-microsoft-prod.deb && \
Fixed!

2022-08-09 06:07 UTC, HollowMan6 commented on Dockerfile
> +    cargo install cfg_me && \
Fixed!

2022-08-09 06:07 UTC, HollowMan6 commented on Dockerfile
> +    mkdir -p /tmp/tmpcargobin && cp /root/.cargo/bin/* /tmp/tmpcargobin && \
Fixed!

2022-08-09 06:08 UTC, HollowMan6 commented on .github/workflows/ci.yml
> +          sudo -E XDG_RUNTIME_DIR= podman exec -i cadr bash -c "cd CADR && make BUILD_DIR=/CADR/build SPLIT_STRATEGY=upgrade test-here-upgrade-${{ matrix.package }}"
Fixed!

2022-08-09 06:27 UTC, HollowMan6 commented
Hi @Kixunil ! Thanks so much for your reviewing, I have made all the change requests and now it continue running 
 smoothly: https://github.com/HollowMan6/build-cryptoanarchy-deb-repo-builder/actions/runs/2822702454

Except that, I noticed you also merged https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder/pull/197#issuecomment-1133664460 , there I mentioned a test failure earlier, and now it still applies to the `bitcoin-restest` packages:

```bash
Generating 150 blocks to address 
--2022-05-21 16:08:34--  http://127.0.0.1:18442/
Connecting to 127.0.0.1:18442... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2022-05-21 16:08:34 ERROR 500: Internal Server Error.
```

Actually I still have no idea on how to fix this, so I guess for the CI to pass, maybe we can revert #197 temporarily.

In addition, #196 works OK and I suggest you to merge that.

Any further review about this PR is welcome, very glad to see this PR moving forward!

2022-08-09 09:22 UTC, Kixunil commented
That's weird, the test passed at my machine. I'm going to clean up and retry just in case and then investigate.

2022-08-10 08:04 UTC, HollowMan6 commented
@Kixunil Just refactored the ci for it to look clean.

After
- #205 

gets merged, there would be nothing stops passing the CI, so this can be merged then, too.

I would recommend merging #196 at the same time since the test also passes and the log's place is also correct.

2022-08-11 02:46 UTC, HollowMan6 commented
> Hi, sorry, I had my testing setup messed up and had trouble testing but I figured it out and merged some. I will look at the others soon. This week is realistic.

Hi @Kixunil , if you need to propose more change requests, since it's Thursday now, it would be great to propose all those today, and because of the time zone difference, I can look into it tomorrow and then you can merge, so that we can finish the project in time. Thanks!

2022-08-12 13:57 UTC, HollowMan6 commented
> @Kixunil Just refactored the ci for it to look clean.
> 
> After
> 
> * [Fix tests for bitcoin-regtest after setting bitcoind nosettings enabled #205](https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder/pull/205)
> 
> gets merged, there would be nothing stops passing the CI https://github.com/HollowMan6/build-cryptoanarchy-deb-repo-builder/actions/runs/2830947782 , so this can be merged then, too.
> 
> I would recommend merging #196 at the same time since the test also passes and the log's place is also correct.

Hi @Kixunil , can I expect all this to get merged today?

2022-08-13 01:04 UTC, Kixunil commented
Oh, by end of week you meant friday, not sunday? Damn. CI is running now, I'm going to sleep and merge it right after it finishes.

2022-08-13 01:15 UTC, HollowMan6 commented
> Oh, by end of week you meant friday, not sunday? Damn. CI is running now, I'm going to sleep and merge it right after it finishes.

Thank you! If Sunday is OK for you, that would be great! I was thinking if you would take some rest then, after all it's the weekend. 👍

2022-08-13 08:11 UTC, Kixunil commented
What's a weekend and what is a rest? :rofl: Anyway, thanks a lot, awesome work!

2022-08-13 08:11 UTC, merged

2022-08-13 10:31 UTC, HollowMan6 commented
Something to note that sometimes the test job can fail due to some systemd service starting timeout issues, this can be fixed by manually re-running the failed jobs https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder/runs/7818421004?check_suite_focus=true

![image](https://user-images.githubusercontent.com/43995067/184479827-ef2a0ff8-dcb8-4901-bcf8-b3b47a58be94.png)

2022-08-13 12:33 UTC, Kixunil commented
I'd like to bump the timeout instead. Did it happen for other services too?

2022-08-13 12:42 UTC, HollowMan6 commented
> I'd like to bump the timeout instead. Did it happen for other services too?

Yeah, not only ridetheln-system, it do happens from time to time for other services, too. Such as: https://github.com/HollowMan6/build-cryptoanarchy-deb-repo-builder/runs/7763326851?check_suite_focus=true

2022-08-13 12:44 UTC, Kixunil commented
Hmm, bitcoind already has timeout bumped. This could be a deeper issue.

2022-08-13 12:50 UTC, HollowMan6 commented
Maybe. That's really strange, and it will be hard to find out the cause for such an issue that happens rarely but can do happen.

2022-08-13 13:03 UTC, Kixunil commented
It could also be just slow CI. It builds the whole thing in 1.5 hours, which, if I remember correctly, my machine can do significantly faster.

2022-08-13 13:06 UTC, HollowMan6 commented
Yeah, after all they just use a 2-core CPU, which would definitely be slow: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources